# Generated by Django 6.0.2 on 2026-09-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dropoff_locations',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off')], max_length=10)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pickup_assigned', 'Pickup Assigned'), ('collected', 'Collected'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='containers.container')),
            ],
            options={
                'db_table': 'returns',
                'ordering': ['-requested_at'],
            },
        ),
    ]
