# Generated by Django 6.0.2 on 2026-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_code', models.CharField(max_length=30, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('pickup_assigned', 'Pickup Assigned'), ('collected', 'Collected'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='excellent', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_returned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'containers',
                'ordering': ['-created_at'],
            },
        ),
    ]
